all:
  vars:
    ip_master: 192.168.1.220
  children:
    clusterhat:
      hosts:
        clusterhatctrl:
          ansible_host: 192.168.1.224
    nodes:
      hosts:
        p1:
          ansible_host: 192.168.1.225
        p2:
          ansible_host: 192.168.1.226
        p3:
          ansible_host: 192.168.1.227
        p4:
          ansible_host: 192.168.1.228
