
- name: determine swarm status
  shell: >
    docker info 2>/dev/null | egrep 'Swarm: ' | cut -d ':' -f2
  register: swarm_result
  changed_when: False


- name: join manager
  shell: >
    docker swarm join
    --token="{{ varswdocker }}"
    192.168.1.224:2377
  when: "' inactive' in swarm_result.stdout_lines"
  ignore_errors: True
